const name = prompt('Type your full name: ')
document.body.innerHTML += `Your name is: ${name} </br>`
document.body.innerHTML += `Your name lenght is: ${name.split(' ').join('').length} </br>`
document.body.innerHTML += `Your second letter of your name is: ${name[1]} </br>`
document.body.innerHTML += `The first letter 'a' in your name is at index: ${name.indexOf('a')} </br>`
document.body.innerHTML += `The last letter 'a' in your name is at index: ${name.lastIndexOf('a')} </br>`
document.body.innerHTML += `The last 3 letters of your name are: ${name.slice(-3)} </br>`
document.body.innerHTML += `The words in your name are: ${name.split(' ')} </br>`
document.body.innerHTML += `Your name with uppercase letters: ${name.toUpperCase()} </br>`
document.body.innerHTML += `Your name with lowercase letters: ${name.toLowerCase()} </br>`
